# Generated by Django 4.0.2 on 2022-02-03 12:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SellHub', '0003_alter_profiluzytkownika_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiluzytkownika',
            name='phone',
            field=models.CharField(blank=True, max_length=60, null=True, validators=[django.core.validators.RegexValidator(message='Numer telefonu musi zaczynac od +48 i mieć 9 cyfr', regex='^[+](48)\\d{9}$')]),
        ),
    ]
