# Generated by Django 4.0.2 on 2022-02-03 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SellHub', '0004_alter_profiluzytkownika_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiluzytkownika',
            old_name='phone',
            new_name='numer_telefonu',
        ),
    ]
