# Generated by Django 4.0.2 on 2022-02-03 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SellHub', '0005_rename_phone_profiluzytkownika_numer_telefonu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ogloszenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=100)),
                ('marka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marka_ogloszenie', to='SellHub.marka')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_ogloszenie', to='SellHub.model')),
            ],
        ),
        migrations.AlterField(
            model_name='profiluzytkownika',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.CreateModel(
            name='ZdjecieOgloszenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ogloszenie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zdjecie_ogloszenie', to='SellHub.ogloszenie')),
            ],
        ),
        migrations.AddField(
            model_name='ogloszenie',
            name='ogloszenie_uzytkownika',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ogloszenie_uzytkownik', to='SellHub.profiluzytkownika'),
        ),
    ]
