# Generated by Django 4.0.2 on 2022-02-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SellHub', '0006_marka_model_ogloszenie_alter_profiluzytkownika_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zdjecieogloszenie',
            name='zdjecie',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
