# Generated by Django 4.0.2 on 2022-02-03 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SellHub', '0007_zdjecieogloszenie_zdjecie'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='marka',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marka', to='SellHub.marka'),
        ),
    ]
