# Generated by Django 4.0.2 on 2022-02-03 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SellHub', '0008_model_marka'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marka',
            old_name='tytul',
            new_name='nazwa',
        ),
        migrations.RenameField(
            model_name='model',
            old_name='tytul',
            new_name='nazwa',
        ),
    ]
