# Generated by Django 4.0.2 on 2022-02-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SellHub', '0009_rename_tytul_marka_nazwa_rename_tytul_model_nazwa'),
    ]

    operations = [
        migrations.AddField(
            model_name='ogloszenie',
            name='cena',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='ogloszenie',
            name='moc_silinka',
            field=models.DecimalField(decimal_places=0, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='ogloszenie',
            name='nadwozie',
            field=models.CharField(choices=[('Kabriolet', 'Kabriolet'), ('Sedan', 'Sedan'), ('Coupe', 'Couoe'), ('Hatchback', 'Kombi'), ('SUV', 'SUV')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='ogloszenie',
            name='negocjacja',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='ogloszenie',
            name='opis',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ogloszenie',
            name='paliwo',
            field=models.CharField(choices=[('Benzyna', 'Benzyna'), ('Diesel', 'Diesel'), ('LPG', 'LPG'), ('Hybryda', 'Hybryda')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='ogloszenie',
            name='rok_produkcji',
            field=models.DecimalField(decimal_places=0, max_digits=4, null=True),
        ),
    ]
