# Generated by Django 4.0.2 on 2022-02-04 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SellHub', '0010_ogloszenie_cena_ogloszenie_moc_silinka_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiluzytkownika',
            name='imie',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profiluzytkownika',
            name='nazwisko',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
