# Generated by Django 4.0.2 on 2022-02-07 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SellHub', '0013_alter_ogloszenie_cena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='marka',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marka_set', to='SellHub.marka'),
        ),
    ]
