# Generated by Django 4.0.2 on 2022-02-07 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SellHub', '0014_alter_model_marka'),
    ]

    operations = [
        migrations.AddField(
            model_name='ogloszenie',
            name='pojemnosc_silnika',
            field=models.DecimalField(decimal_places=0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='ogloszenie',
            name='przebieg',
            field=models.DecimalField(decimal_places=0, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='ogloszenie',
            name='skrzynia_biegow',
            field=models.CharField(choices=[('Manualna', 'Manualna'), ('Automatyczna', 'Automatyczna')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='ogloszenie',
            name='stan_techniczny',
            field=models.CharField(choices=[('Nieuszkodzony', ' Nieuszkodzony'), ('Uszkodzony', 'Uszkodzony')], max_length=15, null=True),
        ),
    ]
