# Generated by Django 4.0.2 on 2022-02-07 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SellHub', '0015_ogloszenie_pojemnosc_silnika_ogloszenie_przebieg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ogloszenie',
            name='negocjacja',
            field=models.CharField(choices=[('Tak', 'Tak'), ('Nie', 'Nie')], max_length=10, null=True),
        ),
    ]
