# Generated by Django 4.0.2 on 2022-02-08 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SellHub', '0016_alter_ogloszenie_negocjacja'),
    ]

    operations = [
        migrations.AddField(
            model_name='ogloszenie',
            name='data_dodania',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='ogloszenie',
            name='nadwozie',
            field=models.CharField(choices=[('Kabriolet', 'Kabriolet'), ('Sedan', 'Sedan'), ('Coupe', 'Coupe'), ('Hatchback', 'Kombi'), ('SUV', 'SUV')], max_length=30, null=True),
        ),
    ]
