# Generated by Django 4.0.2 on 2022-02-08 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SellHub', '0018_alter_profiluzytkownika_numer_telefonu'),
    ]

    operations = [
        migrations.AddField(
            model_name='zdjecieogloszenie',
            name='zdjecie_glowne',
            field=models.BooleanField(default=False),
        ),
    ]
