# Generated by Django 4.0.2 on 2022-02-14 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SellHub', '0019_zdjecieogloszenie_zdjecie_glowne'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obiekt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
            ],
        ),
    ]
