# Generated by Django 4.0.2 on 2022-02-14 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SellHub', '0021_obiekt_typ'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Obiekt',
        ),
    ]
