# Generated by Django 4.0.2 on 2022-02-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SellHub', '0022_delete_obiekt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ogloszenie',
            name='rok_produkcji',
            field=models.DateTimeField(null=True),
        ),
    ]
