# Generated by Django 4.0.2 on 2022-02-15 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SellHub', '0023_alter_ogloszenie_rok_produkcji'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ogloszenie',
            name='moc_silinka',
            field=models.DecimalField(decimal_places=0, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='ogloszenie',
            name='pojemnosc_silnika',
            field=models.DecimalField(decimal_places=0, max_digits=9, null=True),
        ),
    ]
