# Generated by Django 4.0.2 on 2022-02-15 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SellHub', '0024_alter_ogloszenie_moc_silinka_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ogloszenie',
            name='przebieg',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True),
        ),
    ]
