# Generated by Django 4.0.2 on 2022-02-17 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SellHub', '0027_alter_profiluzytkownika_ulubione_ogloszenia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiluzytkownika',
            name='ulubione_ogloszenia',
            field=models.ManyToManyField(blank=True, related_name='ulubione', to='SellHub.Ogloszenie'),
        ),
    ]
