# Generated by Django 4.0.2 on 2022-02-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SellHub', '0029_ogloszenie_wyswietlenia'),
    ]

    operations = [
        migrations.AddField(
            model_name='ogloszenie',
            name='ilosc_ulubionych',
            field=models.IntegerField(default=0),
        ),
    ]
